In [2]:
import numpy as np 


In [3]:
# Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items 
# on Zomato. Use slicing to extract the ratings given by the second and third users only.

rating = np.array([
    [4.5, 4.1, 4.8, 3.9, 4.2],
    [4.1, 4.6, 4.3, 4.3, 4.7],
    [3.8, 4.5, 4.2, 4.6, 4.1],
    [4.7, 4.3, 4.9, 4.5, 4.5]
])

print(rating)
print('\n')

print(rating[1:3,:])


[[4.5 4.1 4.8 3.9 4.2]
 [4.1 4.6 4.3 4.3 4.7]
 [3.8 4.5 4.2 4.6 4.1]
 [4.7 4.3 4.9 4.5 4.5]]


[[4.1 4.6 4.3 4.3 4.7]
 [3.8 4.5 4.2 4.6 4.1]]


In [23]:
# 2.Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select
#  only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong>
#  Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>


steps = np.array([10000,5000,3000,9596,801,8003,12000,3333,666,342])

high_Steps = steps[steps>8000]
print(f"high steps are := {high_Steps}")

high steps are := [10000  9596  8003 12000]


In [21]:
# Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from 
# matches 2, 5, and 7, and print them.


scores = np.array([180, 145, 210, 165, 195, 175, 220, 155])

select_score = scores[[1,4,6]]

li=[]
for i in select_score:
    li.append(int(i))
print(li)

[145, 195, 220]


In [35]:
# 4.Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 
# 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong>
# Do not use any loops.</em>

product = np.array([110,250,300,220,500,600,100,150])
discount = product*0.10
final_price = product - discount
final_price

array([ 99., 225., 270., 198., 450., 540.,  90., 135.])

In [39]:
# 5.Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify,
#  use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.

rating = np.array([5,5.2,-1,0,-2])

filter1 = rating[rating < 0 ] = 0
print(rating)

[5.  5.2 0.  0.  0. ]
