In [1]:
import numpy as np

In [16]:
# 1.Create two NumPy arrays representing the daily step counts of two friends over a week and use
#  element-wise addition, subtraction, multiplication, and division to compare their activity levels.

a = np.array([1000,2000,5000,3333,6784,8986,7684])
b = np.array([2000,5003,5784,9938,7483,849,444])

print(f"addition  =  {a+b}")
print(f"subtraction is = {b-a}")
print(f"multiplication is = {a*b}")

print(f"devision is = {a/b}")

addition  =  [ 3000  7003 10784 13271 14267  9835  8128]
subtraction is = [ 1000  3003   784  6605   699 -8137 -7240]
multiplication is = [ 2000000 10006000 28920000 33123354 50764672  7629114  3411696]
devision is = [ 0.5         0.39976014  0.86445367  0.33537935  0.90658827 10.58421673
 17.30630631]


In [17]:
# 2.Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song 
# interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final 
# recommendation matrix and explain the difference between the two results.


import numpy as np

user_preferences = np.array([
    [5, 2, 1],
    [1, 5, 2],
    [2, 1, 5]
])


song_popularity = np.array([
    [4, 1, 2],
    [2, 5, 1],
    [1, 2, 4]
])

recommendation_dot = np.dot(user_preferences, song_popularity)

recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("Recommendation using dot():")
print(recommendation_dot)

print("\nRecommendation using matmul():")
print(recommendation_matmul)


Recommendation using dot():
[[25 17 16]
 [16 30 15]
 [15 17 25]]

Recommendation using matmul():
[[25 17 16]
 [16 30 15]
 [15 17 25]]


In [44]:
# 3.Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, 
# use transpose (T) to rotate the image and then calculate the mean, median, standard deviation,
# and variance of the pixel values.

a = np.random.randint(300,1000,(4,4))
print(a)
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

print("\n")

Transpose = a.transpose()
print(Transpose)
print(np.mean(Transpose))
print(np.median(Transpose))
print(np.std(Transpose))
print(np.var(Transpose))


[[400 435 920 724]
 [994 669 694 477]
 [814 953 809 810]
 [538 595 704 943]]
717.4375
714.0
183.51054763623262
33676.12109375


[[400 994 814 538]
 [435 669 953 595]
 [920 694 809 704]
 [724 477 810 943]]
717.4375
714.0
183.51054763623262
33676.12109375


In [45]:
# Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(),
#  np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.
#  <br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>


import numpy as np

A = np.array([
    [5, 2, 1],
    [2, 4, 2],
    [1, 2, 5]
])

det = np.linalg.det(A)

inverse = np.linalg.inv(A)

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix:")
print(A)

print("Determinant:")
print(det)

print("Inverse:")
print(inverse)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Matrix:
[[5 2 1]
 [2 4 2]
 [1 2 5]]
Determinant:
63.99999999999998
Inverse:
[[ 0.25  -0.125  0.   ]
 [-0.125  0.375 -0.125]
 [ 0.    -0.125  0.25 ]]
Eigenvalues:
[8. 4. 2.]
Eigenvectors:
[[-5.77350269e-01 -7.07106781e-01  4.08248290e-01]
 [-5.77350269e-01  2.27282281e-16 -8.16496581e-01]
 [-5.77350269e-01  7.07106781e-01  4.08248290e-01]]


In [52]:
# Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two 
# cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then 
# stack both parts vertically.

a = np.array([
             [110,1000,1000,3000,5000,6000],
             [999,324,22,66,773,998]
             ] )

print(f"reshape the data := {a.reshape(3,4)}")


reshape the data := [[ 110 1000 1000 3000]
 [5000 6000  999  324]
 [  22   66  773  998]]
