In [ ]:
# 1.Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py
#  and import numpy as np at the top.

# pip install numpy

In [2]:
import numpy as np

In [6]:
# Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram
#  influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, 
# and data type.

followers = np.array([1200, 15000, 67000, 340000, 1250000])
print(followers)
print(followers.shape)
print(followers.ndim)

[   1200   15000   67000  340000 1250000]
(5,)
1


In [ ]:
# Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. 
# Print the array and its size.

zometo_id = np.arange(101,111)
print(zometo_id)
print(zometo_id.size)



[101 102 103 104 105 106 107 108 109 110]
10


In [11]:
# Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify
#  playlist feature. Print the matrix and explain what the diagonal values represent in a comment.

three_by_three = np.eye(3)
print(three_by_three)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize
#  attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong> Use
#  np.array() for conversion and .itemsize for memory size.</em>


pylist =  [45, 67, 120, 89, 54]

nparray = np.array(pylist)
print(pylist)
print(nparray)

print(nparray.itemsize)


[45, 67, 120, 89, 54]
[ 45  67 120  89  54]
8
